// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Patient is an object representing the database table.
type Patient struct {
	ID         uint        `boil:"ID" json:"ID" toml:"ID" yaml:"ID"`
	PatientID  null.String `boil:"patient_id" json:"patient_id,omitempty" toml:"patient_id" yaml:"patient_id,omitempty"`
	HospitalID uint        `boil:"hospital_id" json:"hospital_id" toml:"hospital_id" yaml:"hospital_id"`
	Serialid   uint        `boil:"serialid" json:"serialid" toml:"serialid" yaml:"serialid"`
	Trialgroup int         `boil:"trialgroup" json:"trialgroup" toml:"trialgroup" yaml:"trialgroup"`
	Initial    null.String `boil:"initial" json:"initial,omitempty" toml:"initial" yaml:"initial,omitempty"`
	Birthdate  null.Time   `boil:"birthdate" json:"birthdate,omitempty" toml:"birthdate" yaml:"birthdate,omitempty"`
	Female     null.Bool   `boil:"female" json:"female,omitempty" toml:"female" yaml:"female,omitempty"`
	Age        null.Int    `boil:"age" json:"age,omitempty" toml:"age" yaml:"age,omitempty"`
	Allowdate  null.Time   `boil:"allowdate" json:"allowdate,omitempty" toml:"allowdate" yaml:"allowdate,omitempty"`
	Startdate  null.Time   `boil:"startdate" json:"startdate,omitempty" toml:"startdate" yaml:"startdate,omitempty"`
	Dropdate   null.Time   `boil:"dropdate" json:"dropdate,omitempty" toml:"dropdate" yaml:"dropdate,omitempty"`
	Dropout    null.Bool   `boil:"dropout" json:"dropout,omitempty" toml:"dropout" yaml:"dropout,omitempty"`
	Finishdate null.Time   `boil:"finishdate" json:"finishdate,omitempty" toml:"finishdate" yaml:"finishdate,omitempty"`

	R *patientR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L patientL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PatientColumns = struct {
	ID         string
	PatientID  string
	HospitalID string
	Serialid   string
	Trialgroup string
	Initial    string
	Birthdate  string
	Female     string
	Age        string
	Allowdate  string
	Startdate  string
	Dropdate   string
	Dropout    string
	Finishdate string
}{
	ID:         "ID",
	PatientID:  "patient_id",
	HospitalID: "hospital_id",
	Serialid:   "serialid",
	Trialgroup: "trialgroup",
	Initial:    "initial",
	Birthdate:  "birthdate",
	Female:     "female",
	Age:        "age",
	Allowdate:  "allowdate",
	Startdate:  "startdate",
	Dropdate:   "dropdate",
	Dropout:    "dropout",
	Finishdate: "finishdate",
}

// Generated where

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}

var PatientWhere = struct {
	ID         whereHelperuint
	PatientID  whereHelpernull_String
	HospitalID whereHelperuint
	Serialid   whereHelperuint
	Trialgroup whereHelperint
	Initial    whereHelpernull_String
	Birthdate  whereHelpernull_Time
	Female     whereHelpernull_Bool
	Age        whereHelpernull_Int
	Allowdate  whereHelpernull_Time
	Startdate  whereHelpernull_Time
	Dropdate   whereHelpernull_Time
	Dropout    whereHelpernull_Bool
	Finishdate whereHelpernull_Time
}{
	ID:         whereHelperuint{field: "`patients`.`ID`"},
	PatientID:  whereHelpernull_String{field: "`patients`.`patient_id`"},
	HospitalID: whereHelperuint{field: "`patients`.`hospital_id`"},
	Serialid:   whereHelperuint{field: "`patients`.`serialid`"},
	Trialgroup: whereHelperint{field: "`patients`.`trialgroup`"},
	Initial:    whereHelpernull_String{field: "`patients`.`initial`"},
	Birthdate:  whereHelpernull_Time{field: "`patients`.`birthdate`"},
	Female:     whereHelpernull_Bool{field: "`patients`.`female`"},
	Age:        whereHelpernull_Int{field: "`patients`.`age`"},
	Allowdate:  whereHelpernull_Time{field: "`patients`.`allowdate`"},
	Startdate:  whereHelpernull_Time{field: "`patients`.`startdate`"},
	Dropdate:   whereHelpernull_Time{field: "`patients`.`dropdate`"},
	Dropout:    whereHelpernull_Bool{field: "`patients`.`dropout`"},
	Finishdate: whereHelpernull_Time{field: "`patients`.`finishdate`"},
}

// PatientRels is where relationship names are stored.
var PatientRels = struct {
}{}

// patientR is where relationships are stored.
type patientR struct {
}

// NewStruct creates a new relationship struct
func (*patientR) NewStruct() *patientR {
	return &patientR{}
}

// patientL is where Load methods for each relationship are stored.
type patientL struct{}

var (
	patientAllColumns            = []string{"ID", "patient_id", "hospital_id", "serialid", "trialgroup", "initial", "birthdate", "female", "age", "allowdate", "startdate", "dropdate", "dropout", "finishdate"}
	patientColumnsWithoutDefault = []string{"patient_id", "hospital_id", "serialid", "trialgroup", "initial", "birthdate", "female", "age", "allowdate", "startdate", "dropdate", "dropout", "finishdate"}
	patientColumnsWithDefault    = []string{"ID"}
	patientPrimaryKeyColumns     = []string{"ID"}
)

type (
	// PatientSlice is an alias for a slice of pointers to Patient.
	// This should generally be used opposed to []Patient.
	PatientSlice []*Patient
	// PatientHook is the signature for custom Patient hook methods
	PatientHook func(context.Context, boil.ContextExecutor, *Patient) error

	patientQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	patientType                 = reflect.TypeOf(&Patient{})
	patientMapping              = queries.MakeStructMapping(patientType)
	patientPrimaryKeyMapping, _ = queries.BindMapping(patientType, patientMapping, patientPrimaryKeyColumns)
	patientInsertCacheMut       sync.RWMutex
	patientInsertCache          = make(map[string]insertCache)
	patientUpdateCacheMut       sync.RWMutex
	patientUpdateCache          = make(map[string]updateCache)
	patientUpsertCacheMut       sync.RWMutex
	patientUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var patientBeforeInsertHooks []PatientHook
var patientBeforeUpdateHooks []PatientHook
var patientBeforeDeleteHooks []PatientHook
var patientBeforeUpsertHooks []PatientHook

var patientAfterInsertHooks []PatientHook
var patientAfterSelectHooks []PatientHook
var patientAfterUpdateHooks []PatientHook
var patientAfterDeleteHooks []PatientHook
var patientAfterUpsertHooks []PatientHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Patient) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Patient) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Patient) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Patient) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Patient) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Patient) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Patient) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Patient) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Patient) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPatientHook registers your hook function for all future operations.
func AddPatientHook(hookPoint boil.HookPoint, patientHook PatientHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		patientBeforeInsertHooks = append(patientBeforeInsertHooks, patientHook)
	case boil.BeforeUpdateHook:
		patientBeforeUpdateHooks = append(patientBeforeUpdateHooks, patientHook)
	case boil.BeforeDeleteHook:
		patientBeforeDeleteHooks = append(patientBeforeDeleteHooks, patientHook)
	case boil.BeforeUpsertHook:
		patientBeforeUpsertHooks = append(patientBeforeUpsertHooks, patientHook)
	case boil.AfterInsertHook:
		patientAfterInsertHooks = append(patientAfterInsertHooks, patientHook)
	case boil.AfterSelectHook:
		patientAfterSelectHooks = append(patientAfterSelectHooks, patientHook)
	case boil.AfterUpdateHook:
		patientAfterUpdateHooks = append(patientAfterUpdateHooks, patientHook)
	case boil.AfterDeleteHook:
		patientAfterDeleteHooks = append(patientAfterDeleteHooks, patientHook)
	case boil.AfterUpsertHook:
		patientAfterUpsertHooks = append(patientAfterUpsertHooks, patientHook)
	}
}

// One returns a single patient record from the query.
func (q patientQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Patient, error) {
	o := &Patient{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for patients")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Patient records from the query.
func (q patientQuery) All(ctx context.Context, exec boil.ContextExecutor) (PatientSlice, error) {
	var o []*Patient

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Patient slice")
	}

	if len(patientAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Patient records in the query.
func (q patientQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count patients rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q patientQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if patients exists")
	}

	return count > 0, nil
}

// Patients retrieves all the records using an executor.
func Patients(mods ...qm.QueryMod) patientQuery {
	mods = append(mods, qm.From("`patients`"))
	return patientQuery{NewQuery(mods...)}
}

// FindPatient retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPatient(ctx context.Context, exec boil.ContextExecutor, iD uint, selectCols ...string) (*Patient, error) {
	patientObj := &Patient{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `patients` where `ID`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, patientObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from patients")
	}

	return patientObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Patient) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no patients provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(patientColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	patientInsertCacheMut.RLock()
	cache, cached := patientInsertCache[key]
	patientInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			patientAllColumns,
			patientColumnsWithDefault,
			patientColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(patientType, patientMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(patientType, patientMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `patients` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `patients` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `patients` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, patientPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into patients")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == patientMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for patients")
	}

CacheNoHooks:
	if !cached {
		patientInsertCacheMut.Lock()
		patientInsertCache[key] = cache
		patientInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Patient.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Patient) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	patientUpdateCacheMut.RLock()
	cache, cached := patientUpdateCache[key]
	patientUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			patientAllColumns,
			patientPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update patients, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `patients` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, patientPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(patientType, patientMapping, append(wl, patientPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update patients row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for patients")
	}

	if !cached {
		patientUpdateCacheMut.Lock()
		patientUpdateCache[key] = cache
		patientUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q patientQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for patients")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for patients")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PatientSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), patientPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `patients` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, patientPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in patient slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all patient")
	}
	return rowsAff, nil
}

var mySQLPatientUniqueColumns = []string{
	"ID",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Patient) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no patients provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(patientColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLPatientUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	patientUpsertCacheMut.RLock()
	cache, cached := patientUpsertCache[key]
	patientUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			patientAllColumns,
			patientColumnsWithDefault,
			patientColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			patientAllColumns,
			patientPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert patients, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "patients", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `patients` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(patientType, patientMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(patientType, patientMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for patients")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == patientMapping["ID"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(patientType, patientMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for patients")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for patients")
	}

CacheNoHooks:
	if !cached {
		patientUpsertCacheMut.Lock()
		patientUpsertCache[key] = cache
		patientUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Patient record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Patient) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Patient provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), patientPrimaryKeyMapping)
	sql := "DELETE FROM `patients` WHERE `ID`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from patients")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for patients")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q patientQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no patientQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from patients")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for patients")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PatientSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(patientBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), patientPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `patients` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, patientPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from patient slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for patients")
	}

	if len(patientAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Patient) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPatient(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PatientSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PatientSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), patientPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `patients`.* FROM `patients` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, patientPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PatientSlice")
	}

	*o = slice

	return nil
}

// PatientExists checks if the Patient row exists.
func PatientExists(ctx context.Context, exec boil.ContextExecutor, iD uint) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `patients` where `ID`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if patients exists")
	}

	return exists, nil
}
